"""Tests for the egress allowlist.

The container can reach the model, GitHub and its resolver, and nothing else.
That is a property of a ruleset built as a value, so it is asserted here on the
text `nft` would read -- with no daemon, no network and no capability.
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from pathlib import Path

import pytest
from fake_proc import FakeRunner

from pi_agent import _proc
from pi_agent.container import egress

META = json.dumps(
    {
        "git": ["140.82.112.0/20", "2a0a:a440::/29"],
        "api": ["140.82.112.0/20", "143.55.64.0/20"],
        "web": ["185.199.108.0/22"],
        "hooks": ["192.30.252.0/22"],
    }
)

POLICY = egress.Policy(
    model_ip="100.64.0.1",
    model_port=8080,
    resolvers=("192.168.65.7",),
    github=("140.82.112.0/20", "143.55.64.0/20"),
    allowed=("151.101.0.223",),
)


def rules(policy: egress.Policy) -> list[str]:
    """The chain's rules, stripped, in order: the lines indented two levels."""
    return [
        line.strip() for line in egress.ruleset(policy).splitlines() if line.startswith(" " * 8)
    ]


# ------------------------------------------------------------- the ruleset


def test_everything_not_allowed_is_rejected() -> None:
    """The policy is drop, and the last two rules reject explicitly so a blocked
    connection fails at once rather than costing the model a timeout."""
    text = egress.ruleset(POLICY)

    assert "type filter hook output priority filter; policy drop;" in text
    assert rules(POLICY)[-2:] == ["meta l4proto tcp reject with tcp reset", "reject"]


def test_the_model_is_reachable_on_its_port_and_no_other() -> None:
    assert "ip daddr 100.64.0.1 tcp dport 8080 accept" in rules(POLICY)
    assert "ip daddr 100.64.0.1 tcp dport 443 accept" not in rules(POLICY)


def test_github_and_the_allowed_hosts_are_reachable_on_https_only() -> None:
    text = egress.ruleset(POLICY)

    assert "elements = { 140.82.112.0/20, 143.55.64.0/20, 151.101.0.223 }" in text
    assert "ip daddr @https4 tcp dport 443 accept" in rules(POLICY)
    assert "dport 80 " not in text


def test_dns_goes_only_to_the_resolver_docker_provided() -> None:
    """DNS is a channel too; a run may ask exactly the resolver it was given."""
    chain = rules(POLICY)

    assert "ip daddr 192.168.65.7 udp dport 53 accept" in chain
    assert "ip daddr 192.168.65.7 tcp dport 53 accept" in chain
    assert sum("dport 53" in rule for rule in chain) == 2


def test_loopback_stays_open() -> None:
    """pi and the tools it runs talk to themselves; that is not egress."""
    assert 'oif "lo" accept' in rules(POLICY)


def test_a_family_with_no_members_emits_no_set() -> None:
    """nft refuses `elements = { }`, so an IPv4-only policy must not mention v6."""
    text = egress.ruleset(POLICY)

    assert "https6" not in text
    assert "ip6" not in text


def test_ipv6_ranges_get_their_own_set_and_rule() -> None:
    dual = egress.Policy(
        model_ip="fd7a:115c:a1e0::1",
        model_port=8080,
        resolvers=("192.168.65.7", "fd00::53"),
        github=("140.82.112.0/20", "2a0a:a440::/29"),
        allowed=(),
    )
    text = egress.ruleset(dual)
    chain = rules(dual)

    assert "set https6 { type ipv6_addr; flags interval; elements = { 2a0a:a440::/29 } }" in text
    assert "ip6 daddr @https6 tcp dport 443 accept" in chain
    assert "ip6 daddr fd7a:115c:a1e0::1 tcp dport 8080 accept" in chain
    assert "ip6 daddr fd00::53 udp dport 53 accept" in chain


# ------------------------------------------------------------- the inputs


def test_github_ranges_come_from_meta_for_git_api_and_web_only() -> None:
    """hooks, pages and packages are GitHub too, and a run has no business there."""
    runner = FakeRunner([("/meta", META)])

    ranges = egress.github_ranges("ghs_token", env={}, run=runner)

    assert ranges == ("140.82.112.0/20", "2a0a:a440::/29", "143.55.64.0/20", "185.199.108.0/22")
    assert runner.commands == ["gh api --method GET /meta"]
    assert runner.environments[0] == {"GH_TOKEN": "ghs_token"}


def test_a_meta_without_a_range_family_is_an_error_not_an_open_network() -> None:
    runner = FakeRunner([("/meta", json.dumps({"git": ["140.82.112.0/20"], "api": []}))])

    with pytest.raises(egress.EgressError, match="'api'"):
        egress.github_ranges("ghs_token", env={}, run=runner)


def test_a_failed_meta_fetch_stops_the_run() -> None:
    runner = FakeRunner(failures=["/meta"])

    with pytest.raises(egress.EgressError, match="address ranges"):
        egress.github_ranges("ghs_token", env={}, run=runner)


def test_the_resolvers_are_read_from_resolv_conf(tmp_path: Path) -> None:
    conf = tmp_path / "resolv.conf"
    conf.write_text("# Generated by Docker Engine.\nnameserver 192.168.65.7\nsearch example\n")

    assert egress.resolvers(conf) == ("192.168.65.7",)


def test_a_resolv_conf_without_a_nameserver_stops_the_run(tmp_path: Path) -> None:
    """Without DNS the clone fails later with a reset that names nothing."""
    conf = tmp_path / "resolv.conf"
    conf.write_text("search example\n")

    with pytest.raises(egress.EgressError, match="no nameserver"):
        egress.resolvers(conf)


def test_allowed_hosts_are_resolved_once_to_every_address_they_have() -> None:
    answers = {"pypi.org": ["151.101.0.223", "151.101.64.223"], "npm.example": ["10.9.8.7"]}

    resolved = egress.resolve_all(
        egress.allowed_hosts(" pypi.org, npm.example ,"), resolve=lambda name: answers[name]
    )

    assert resolved == ("151.101.0.223", "151.101.64.223", "10.9.8.7")


def test_an_allowed_host_that_does_not_resolve_stops_the_run() -> None:
    """A typo would otherwise allow nothing, silently, and fail inside a tool call."""

    def resolve(name: str) -> list[str]:
        raise OSError("Name or service not known")

    with pytest.raises(egress.EgressError, match="cannot resolve EGRESS_ALLOW host nope"):
        egress.resolve_all(("nope",), resolve=resolve)


def test_unset_egress_allow_allows_nothing_extra() -> None:
    assert egress.allowed_hosts(None) == ()
    assert egress.allowed_hosts("") == ()


def test_a_model_address_that_is_not_an_address_is_refused(tmp_path: Path) -> None:
    """It would be an nft syntax error, reported by nft against a temp file."""
    with pytest.raises(egress.EgressError, match="MODEL_IP"):
        egress.policy_for(
            "ghs_token",
            model_ip="model-box",
            model_port=8080,
            allow=None,
            resolv_conf=tmp_path / "absent",
            run=FakeRunner(),
        )


def test_policy_for_gathers_every_input(tmp_path: Path) -> None:
    conf = tmp_path / "resolv.conf"
    conf.write_text("nameserver 192.168.65.7\n")

    policy = egress.policy_for(
        "ghs_token",
        model_ip="100.64.0.1",
        model_port=8080,
        allow="pypi.org",
        resolv_conf=conf,
        resolve=lambda name: ["151.101.0.223"],
        env={},
        run=FakeRunner([("/meta", META)]),
    )

    assert policy == egress.Policy(
        model_ip="100.64.0.1",
        model_port=8080,
        resolvers=("192.168.65.7",),
        github=("140.82.112.0/20", "2a0a:a440::/29", "143.55.64.0/20", "185.199.108.0/22"),
        allowed=("151.101.0.223",),
    )
    assert "model 100.64.0.1:8080, 4 GitHub ranges, 1 allowed addresses" in policy.summary()


# ---------------------------------------------------------------- applying


def test_the_ruleset_reaches_nft_verbatim() -> None:
    """`nft -f` reads a file; what it reads must be exactly what was built."""
    seen: list[str] = []

    def runner(
        argv: Sequence[str],
        *,
        env: Mapping[str, str] | None = None,
        cwd: Path | None = None,
        check: bool = True,
        capture: bool = True,
    ) -> _proc.Result:
        assert argv[:2] == ["nft", "-f"]
        seen.append(Path(argv[2]).read_text(encoding="utf-8"))
        return _proc.Result(tuple(argv), 0, "", "")

    text = egress.ruleset(POLICY)
    egress.apply(text, run=runner)

    assert seen == [text]


def test_a_rejected_ruleset_stops_the_run_rather_than_leaving_it_open() -> None:
    with pytest.raises(egress.EgressError, match="could not install"):
        egress.apply(egress.ruleset(POLICY), run=FakeRunner(failures=["nft"]))
